### PR TITLE
A couple patches

### PR DESCRIPTION
**Pull request by jjcf89**
Never done a pull request before.  Hopefully this works...

### CODE REVIEW

**Comment by amterp** [comment]
Hey jjcf89! Thanks a ton for the contribution, I definitely wasn't expecting that, I'm blown away!

Thanks for integrating cross-platform support, that's definitely something I'll use in the future, as I wasn't aware os.system('cls') was Windows specific. And also thanks for fixing those errors and increasing readability, that's awesome!

I'm curious about the gitignore file, I Googled around a little but I couldn't myself find any use for it, how does it assist you, if I may ask?

**Comment by jjcf89** [comment]
The .gitignore file tells git which files it doesn't need to worry about.  For example if when I open a file and a <filename>.py~ file is created and I don't want git to list it as a untracked file I can create a rule to ignore those files.

https://git-scm.com/docs/gitignore

There is actually a github repo that includes indepth .gitignore files for different languages. And I believe github itself will create you .gitignore if you tell it what language you are using when you create it.
https://github.com/github/gitignore

**Comment by amterp** [comment]
I see, I understand now , thanks a lot! It's a bit curious however, it seems that each individual developer may have their own particular needs, and the gitignore file doesn't seem to ignore itself, so for example, I've added demo.gif to it because I had the gif I posted on reddit in the same folder and I wanted Git to ignore it, but now, if you were to pull the latest version of the master branch, you'd have demo.gif on there too, which seems a bit strange.

Anyway, thanks again! :+1:

**Comment by jjcf89** [comment]
Yeah its not perfect but it doesn't really hurt to ignore things that other people won't have anyways.

On bigger projects, it can happen that someone will add a ignore that unintentionally hides some file they wanted to check in and forgot about.  But it doesn't happen that much.

**Pull request merged**
